---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: dynatrace-standard-components
  namespace: dynatrace
resources:
  - dynakube.yaml
  - gcp-cluster-sealed.yaml
  - kubernetes.yaml
  - namespace.yaml
spec:
  interval: 1m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: dynatrace-operator
      namespace: dynatrace
    - apiVersion: apps/v1
      kind: Deployment
      name: dynatrace-webhook
      namespace: dynatrace