---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dynatrace-custom-components
  namespace: dynatrace
spec:
  dependsOn:
    - name: dynatrace-standard-components
  interval: 1m
  path: "../dynatrace-standard-components"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
resources:
  - dynakube.yaml