---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: dynatrace-oneagent
  namespace: dynatrace
resources:
  - classicFullStack.yaml
  - helmrelease.yaml
  - helmsource.yaml
  - namespace.yaml
  - otel-demo-cluster-sealed.yaml